[workspace]
resolver = "2"
members = [
    "packages/cli",
    "packages/flatbuffers_structs",
    "packages/protocol",
    "packages/vita_reports",
    "packages/vita_virtual_device", "packages/vitaoxipad_config",
]
